import type { Metadata } from "next"
import { PublicPage } from "@/components/site/public-page"
import { HomeLink } from "@/components/ui/home-link"

export const metadata: Metadata = {
  title: "Compare Premiere Pro MCP servers: setup, bridges and workflow evidence",
  description: "Compare four open-source Premiere Pro MCP projects using dated primary sources. Understand CEP and UXP bridges, installation choices, workflow scope, and verification limits.",
  alternates: { canonical: "/compare/" },
}
const projects = [
  { name: "leancoderkavy / premiere-pro-mcp", source: "https://github.com/leancoderkavy/premiere-pro-mcp", setup: "Local Node.js server with CEP compatibility and capability-gated UXP tools.", fit: "Editors who want a searchable tool reference, guided setup, workflow recipes, and explicit released-versus-source availability.", check: "Review the recorded assembly workflow, then verify your own host connection. The recording covers one workflow on Premiere 26.5.0." },
  { name: "hetpatel-11 / Adobe_Premiere_Pro_MCP", source: "https://github.com/hetpatel-11/Adobe_Premiere_Pro_MCP/blob/ee31c3def7c3ca1c68662ea7737a9f8e5a2b634f/README.md", setup: "Node.js 20+, Premiere 2020+, local CEP panel; UXP is described as experimental.", fit: "Clients that benefit from a small always-on surface with search_tools / invoke_tool routing, guided prompts, and multilingual documentation.", check: "The README lists 283 tools and an installer/doctor workflow. Those are project claims, not independent host certification." },
  { name: "ayushozha / AdobePremiereProMCP", source: "https://github.com/ayushozha/AdobePremiereProMCP/blob/914823b84d05030578b65fb10048fcd4dd03ae02/README.md", setup: "Go orchestration, Rust media services, Python intelligence, and a TypeScript CEP bridge.", fit: "Developers evaluating script-to-timeline workflows, asset matching, EDL planning, captions, and broader media automation.", check: "The README distinguishes 1,064 schemas, 932 host commands, and a curated 72-tool standard profile. These are different units; the larger compatibility surface is not uniformly certified." },
  { name: "antipaster / Adobe-Premiere-Pro-MCP", source: "https://github.com/antipaster/Adobe-Premiere-Pro-MCP/blob/9cb62cf9c7f9a64379e0cb1600ff3be93a46cac5/README.md", setup: "Windows, Node.js 18+, Premiere 2023+; Node server connects over WebSocket to a CEP panel.", fit: "Windows users exploring a batch installer, editing and caption tools, and optional ElevenLabs voiceover integration.", check: "The README advertises 170+ tools and says tested on Premiere 2026. Optional voice services need separate configuration; test your exact actions locally." },
]
export default function ComparePage() {
  return <PublicPage><main id="main-content" className="min-h-screen bg-site-bg px-5 py-16 text-site-text sm:py-24"><article className="mx-auto max-w-4xl space-y-10">
    <nav aria-label="Breadcrumb" className="text-sm text-site-muted"><HomeLink href="/">MCP for Adobe Premiere Pro</HomeLink> / Compare</nav>
    <header><p className="font-mono text-sm uppercase text-site-accent">Source review · September 15, 2026</p><h1 className="mt-5 text-4xl font-bold tracking-tight sm:text-6xl">Choose a Premiere Pro MCP server for your workflow.</h1><p className="mt-6 text-lg text-site-muted">Start with your operating system, connection method, and the edit you need to complete. A larger tool catalog alone cannot tell you whether an operation works on your Premiere host.</p></header>
    <p>This guide is maintained by leancoderkavy/premiere-pro-mcp. It compares four established public projects, not every MCP server, and is not an independent benchmark. Other projects’ descriptions come from the linked README revisions reviewed on September 15, 2026; we have not run their tools in Premiere for this comparison.</p>
    {projects.map(project => <section key={project.name} className="space-y-4 rounded-xl border border-site-line p-6"><h2 className="break-words text-2xl font-semibold">{project.name}</h2><dl className="space-y-3"><div><dt className="font-semibold">Setup and bridge</dt><dd>{project.setup}</dd></div><div><dt className="font-semibold">Why evaluate it</dt><dd>{project.fit}</dd></div><div><dt className="font-semibold">What to verify</dt><dd>{project.check}</dd></div></dl><a className="text-site-accent underline" href={project.source}>Read this project’s source documentation</a></section>)}
    <section className="space-y-4"><h2 className="text-2xl font-semibold">Compare the same task on the same host</h2><ol className="list-decimal space-y-3 pl-6"><li>Record your Premiere version, OS, bridge, package version, and enabled tool profile.</li><li>Use a duplicate project and the same three sample clips for each evaluation.</li><li>Inspect the connection, assemble a sequence, add markers, and read back clip positions.</li><li>Check the native timeline and saved project. Record unsupported actions and failures alongside successes.</li></ol><p>Separate registered schemas, default exposed tools, and live supported operations. Stars indicate community interest; they do not establish reliability or feature parity.</p></section>
    <section className="space-y-4"><h2 className="text-2xl font-semibold">Evaluate this project before installing</h2><p><a href="/demo/" className="text-site-accent underline">Watch the recorded workflow and inspect its receipt</a>, search the <a href="/tools/" className="text-site-accent underline">tool catalog</a>, or read the <a href="/facts/" className="text-site-accent underline">release and compatibility facts</a>. Ready to connect? Follow the <a href="/docs/" className="text-site-accent underline">installation guide</a>.</p></section>
  </article></main></PublicPage>
}
